demo1:
  path: /
  controller: App\Controller\HelloController::demo1

# put demo3 route before demo2 for priority
demo3:
  path: /hello/{id}
  requirements: { id: \d+ }
  controller: App\Controller\HelloController::demo3

demo2:
  path: /hello/{name}
  defaults: { name: 'tout le monde' }
  schemes: https
  methods: [GET, POST]
  controller: App\Controller\HelloController::demo2

demo2.fr:
  path: /bonjour/{name}.{format}
  defaults: { name: 'tout le monde', _locale: fr, _format: html }
  schemes: https
  methods: [GET, POST]
  controller: App\Controller\HelloController::demo2
